### ISSUE TITLE
porting LIDAREnhanced to esp32 c++

### ISSUE THREAD

**Issue by ksmith9109** [AlexisTM/LIDAREnchanced#8]
I am studying your code and it looks nice!  My target platform is c++ on the Espressif ESP32 WROVER KIT https://www.adafruit.com/product/3384[](url)

Please confirm that in the statement below:

 LZ1.begin(Z1_LASER_EN, Z1_LASER_PIN, Z1_LASER_TRIG, Z1_LASER_AD, 2, DISTANCE, 'A');

Z1_LASER_EN is the i2c SDA pin  (data)  and
Z1_LASER_PIN is the i2c SCL pin (clock).

When I become more literate, I will be happy to assist with simple velocity codes.
Sincerely

Kent Smith

**Comment by AlexisTM** [comment]
Dear, it is not, sorry. 

* LASER_EN is the Enable pin of the laser. 
* LASER_PIN is the Mode pin of the laser. // Not used, as the PWM mode is very slow
* LASER_TRIG is the Trig pin of the laser. // Not used, as the PWM mode is very slow

I was planning to make a PWM driver as well, but it was way too slow. As well as using the "continuous measurement mode". Therefore, I am only using the I2C interface. 

The LASER_EN pin is used to set the I2C address of the lasers, one by one, and also to reset a laser.

The I2C interface is using the default Wire Arduino library. To make it compatible with another platform which is not compatible with the Wire library, you can edit the I2CFunctions.h file. 

You need to reimplement the functions : begin, write, readByte, readWord.

**Comment by AlexisTM** [comment]
Closed for inactivity
